export const mockPayload = {
  events: [
    {
      event: {
        banner: {
          headline: "",
          subtitle: "",
          emoji: "",
        },
        category: "music",
        center_court: {
          x: 133,
          y: 119,
          width: 11,
          height: 9,
        },
        datetime_local: "2023-06-09T20:00:00",
        datetime_utc: "2023-06-10T01:00:00",
        id: "63f1223f57be6100016545a0",
        map_url: "https://maps.gametime.co/v2/the_criterion/music/music-8.png",
        min_price: {
          total: 0,
          prefee: 0,
        },
        name: "Luis Angel",
        performers: [
          {
            id: "62bf3ef2f366dc0001f71ca9",
            primary: true,
          },
          {
            id: "62bf3ef2f366dc0001f71ca9",
            primary: false,
          },
        ],
        sales_cut_off: "2023-06-10T02:30:00Z",
        section_map_id: "59f241c69da0d48c0d0ae57e",
        tbd: false,
        time_tbd: false,
        date_tbd: false,
        venue_id: "59f2394cfbdab6000e265a3d",
        venue_config: "music",
        related_events: {},
      },
      performers: [
        {
          abbrev: "ELFLACO",
          category: "music",
          category_group: "concert",
          contrast_color: "",
          display_type: "performer_at_venue",
          id: "62bf3ef2f366dc0001f71ca9",
          hero_image_url: "https://images.gametime.co/musicelflaco/hero@4x.jpg",
          medium_name: "Luis Angel",
          name: "Luis Angel",
          primary_color: "7ed321FF",
          short_name: "Luis Angel",
          slug: "musicelflaco",
          meta: {
            score_boost: null,
          },
        },
        {
          abbrev: "ELFLACO",
          category: "music",
          category_group: "concert",
          contrast_color: "",
          display_type: "performer_at_venue",
          id: "62bf3ef2f366dc0001f71ca9",
          hero_image_url: "https://images.gametime.co/musicelflaco/hero@4x.jpg",
          medium_name: "Luis Angel",
          name: "Luis Angel",
          primary_color: "7ed321FF",
          short_name: "Luis Angel",
          slug: "musicelflaco",
          meta: {
            score_boost: null,
          },
        },
      ],
      venue: {
        city: "Oklahoma City",
        id: "59f2394cfbdab6000e265a3d",
        location: {
          lat: 35.4661,
          lon: -97.5041,
        },
        name: "The Criterion",
        show_currency: false,
        slug: "the_criterion",
        state: "OK",
        timezone: "America/Chicago",
        metro: "oklahomacity",
        image_url:
          "https://maps.gametime.co/v2/the_criterion/music/music-8.png",
        meta: {
          score_boost: null,
        },
      },
      meta: {
        search_score: 31.863012,
        sort_order: 1,
        display_group: "top_pick",
        popularity_score: 0,
        score_boost: 0,
      },
    },
  ],
  performers: [
    {
      abbrev: "MIGUEL",
      category: "music",
      category_group: "concert",
      contrast_color: "",
      display_type: "performer_at_venue",
      id: "5a846b0525f2c55b441ec3c1",
      hero_image_url: "https://images.gametime.co/musicluismiguel/hero@4x.jpg",
      medium_name: "Luis Miguel",
      name: "Luis Miguel",
      primary_color: "E6AA90FF",
      short_name: "Luis Miguel",
      slug: "musicluismiguel",
      meta: {
        search_score: 64.10719,
        sort_order: 0,
        display_group: "performers",
        popularity_score: 8.777313396289204e-7,
        score_boost: 0,
      },
    },
  ],
  venues: [
    {
      city: "Oklahoma City",
      id: "61afde36f758120001898101",
      location: {
        lat: 35.5235,
        lon: -97.4725,
      },
      name: "Oklahoma City Zoo Amphitheatre",
      show_currency: false,
      slug: "okc_zoo_amphitheatre",
      state: "OK",
      timezone: "America/Chicago",
      metro: "oklahomacity",
      image_url:
        "https://maps.gametime.co/v2/okc_zoo_amphitheatre/music/music-8.png",
      meta: {
        search_score: 18.490675,
        sort_order: 14,
        display_group: "venues",
        popularity_score: 0.0000018803324764356279,
        score_boost: 0,
      },
    },
  ],
  display_groups: [
    {
      display_name: "Top Result",
      slug: "top_pick",
      sort_order: 0,
    },
    {
      display_name: "Performers",
      slug: "performers",
      sort_order: 1,
    },
    {
      display_name: "Venues",
      slug: "venues",
      sort_order: 2,
    },
    {
      display_name: "Events",
      slug: "events",
      sort_order: 3,
    },
  ],
}
